# 버전 정보
version: 0.2

# 빌드 단계를 정의
phases:
  # 빌드 전 단계
  pre_build:
    commands:
      - cd step2/client
      - npm install  # npm을 이용하여 필요한 패키지들을 설치
  # 빌드 단계
  build:
    commands:
      - npm run build  # npm 스크립트를 통해 빌드 수행

# 빌드 후 생성된 결과물에 대한 정보
artifacts:
  files:
    - '**/*'  # 모든 파일과 디렉토리를 포함
  base-directory: step2/client/build  # 결과물이 위치한 기본 디렉토리는 'build' 
