version: 0.0           # appspec 파일의 버전을 지정
os: linux              # 운영 체제 지정

files:                 # 배포될 파일 및 디렉터리에 대한 정보
  - source: /          # 소스 디렉터리 지정 (루트 디렉터리)
    destination: /home/ubuntu/server-univ  # 대상 디렉터리 지정
    overwrite: yes     # 이미 존재하는 파일 또는 디렉터리를 덮어쓸지 결정

hooks:                 # 배포 생명주기 이벤트에 대한 스크립트 지정
  ApplicationStop:    # 애플리케이션 중지 전에 실행될 스크립트
    - location: scripts/stop.sh   # 실행할 스크립트 위치
      runas: root                 # 스크립트를 실행할 사용자 지정 (여기서는 root 사용자로 실행)
  AfterInstall:       # 파일 및 디렉터리가 복사된 후에 실행될 스크립트
    - location: scripts/initialize.sh   # 실행할 스크립트 위치
      runas: root                           # 스크립트를 실행할 사용자 지정 (여기서는 root 사용자로 실행)
  ApplicationStart:   # 애플리케이션 시작 전에 실행될 스크립트
    - location: scripts/start.sh   # 실행할 스크립트 위치
      runas: root                  # 스크립트를 실행할 사용자 지정 (여기서는 root 사용자로 실행)
